version: '3.8'
services:
  database:
    image: postgres:15.0
    container_name: 'database'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database   
    networks:
      - nestjs-network
networks:
  nestjs-network: